name: im_kit
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_openim_sdk_ffi:
    path: ../flutter_openim_sdk_ffi
  flutter_muka:
    path: ../flutter_muka
  path:
  get:
  url_launcher: 
  just_audio:
  record: ^5.0.0-beta.2
  file_picker: 
  media_kit: 
  media_kit_video:
  media_kit_native_event_loop:
  media_kit_libs_android_video: 
  media_kit_libs_ios_video: 
  media_kit_libs_macos_video: 
  media_kit_libs_windows_video: 
  media_kit_libs_linux:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
