name: im_kit
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/Spicely/im_kit

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_openim_sdk_ffi:
    path: ../../../../im/flutter_openim_sdk_ffi
  flutter_muka:
    git:
      url: https://github.com/Spicely/flutter_muka.git
      ref: v3
  path:
  get:
  audioplayers:
  record: ^5.0.1
  image_gallery_saver:
  card_swiper: 
  photo_view: 
  image: 
  html:
  lottie:
  uuid:
  encrypt: 
  flutter_oss_aliyun: 
  pointycastle:
  popup_menu: 
  chinese_font_library: 
  media_kit: 1.1.10
  media_kit_video: 1.2.4
  media_kit_libs_video: 1.0.4
  extended_text_field:
  bubble_tab_indicator: 
  intl:
  sprintf: 
  url_launcher:
  easy_refresh:
  scrollable_positioned_list:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/json/
    - assets/emoji/
    - assets/icons/