name: im_kit
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/Spicely/im_kit

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_openim_sdk_ffi:
    path: ../flutter_openim_sdk_ffi
  flutter_muka:
    path: ../flutter_muka
  path:
  get:
  audioplayers:
  loading_indicator: 
  record:
  image_gallery_saver:
  card_swiper: 
  photo_view: 
  image: 
  lottie:
  encrypt: 
  pointycastle:
  popup_menu: 
  media_kit: ^1.1.7
  media_kit_video: ^1.1.8
  media_kit_libs_video: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/json/